version: "3.8"

services:
  api-seed:
    user: node
    build: ./
    ports:
      - 3333:3333
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3333/"]
      interval: 30s
      timeout: 10s
      retries: 3
    container_name: api-seed
  mongodb:
    image: mongo
    restart: always
    scale: 0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./mongoData:/data/db