version: "3.8"

services:
  api-seed:
    user: node
    build: ./
    volumes:
      - ./:/api
      - /api/node_modules/
    ports:
      - 3333:3333
    container_name: api-seed
  mongodb:
    image: mongo
    restart: always
    scale: 0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./mongoData:/data/db