# This is a basic workflow to help you get started with Actions

name: Deploy backend code changes

# Controls when the action will run. 
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']
    paths: 'backend/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/telegram-mini-app/backend
          git pull
          git status
          echo "${{ secrets.ENV_VARIABLES }}" > .env
          docker-compose up -d --force-recreate --build
          docker-compose logs --tail=1000
          